export const themes = {
  slate: {
    name: 'Slate',
    description: 'Sombre et focalisé',
    preview: '#0F172A',
    vars: {
      '--bg-base': '#0F172A',
      '--bg-surface': '#1E293B',
      '--bg-elevated': '#334155',
      '--bg-bottom': '#1E293B',
      '--text-primary': '#F1F5F9',
      '--text-secondary': '#94A3B8',
      '--text-muted': '#64748B',
      '--text-hint': '#475569',
      '--accent': '#4338CA',
      '--accent-hover': '#3730A3',
      '--accent-light': '#818CF8',
      '--accent-subtle': '#312E81',
      '--accent-muted': '#C7D2FE',
      '--border-subtle': '#1E293B',
      '--border-default': '#334155',
      '--border-focus': '#818CF8',
      '--btn-non-bg': '#2D1515',
      '--btn-non-text': '#FCA5A5',
      '--btn-non-border': '#991B1B',
      '--btn-hes-bg': '#1A1F2E',
      '--btn-hes-text': '#818CF8',
      '--btn-hes-border': '#4338CA',
      '--btn-oui-bg': '#0C2D1E',
      '--btn-oui-text': '#6EE7B7',
      '--btn-oui-border': '#0F6E56',
      '--reveal-bg': '#4338CA',
      '--reveal-text': '#FFFFFF',
      '--streak-bg': '#0E7490',
      '--streak-text': '#06B6D4',
    }
  },
  linen: {
    name: 'Linen',
    description: 'Clair et aéré',
    preview: '#FAFAF9',
    vars: {
      '--bg-base': '#FAFAF9',
      '--bg-surface': '#F0EFE8',
      '--bg-elevated': '#E5E5DF',
      '--bg-bottom': '#FFFFFF',
      '--text-primary': '#1C1A17',
      '--text-secondary': '#3D3830',
      '--text-muted': '#6B6459',
      '--text-hint': '#8A8278',
      '--accent': '#3D5A9A',
      '--accent-hover': '#2D4A8A',
      '--accent-light': '#5A7ABA',
      '--accent-subtle': '#E8EDF8',
      '--accent-muted': '#B8C8E8',
      '--border-subtle': '#EDECE6',
      '--border-default': '#E0DED8',
      '--border-focus': '#3D5A9A',
      '--btn-non-bg': '#FDF2EF',
      '--btn-non-text': '#993C1D',
      '--btn-non-border': '#F5C4B3',
      '--btn-hes-bg': '#F7F7F5',
      '--btn-hes-text': '#6B6459',
      '--btn-hes-border': '#E0DED8',
      '--btn-oui-bg': '#F0F8F3',
      '--btn-oui-text': '#3B6D11',
      '--btn-oui-border': '#C0DD97',
      '--reveal-bg': '#1C1A17',
      '--reveal-text': '#FAFAF9',
      '--streak-bg': '#FEF9ED',
      '--streak-text': '#C9963A',
    }
  }
} as const

export type ThemeKey = keyof typeof themes
